apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "wsp-database.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wsp-database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wsp-database.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.spec.restartPolicy }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.spec.volumes.dataPath }}
            type: Directory
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              protocol: {{ .Values.service.protocol }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: timezone
              mountPath: /etc/timezone
              readOnly: true
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
          env:
            - name: TZ
              value: {{ .Values.spec.timeZone }}
            - name: PGTZ
              value: {{ .Values.spec.pgTimeZone }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}