apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openvpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openvpn.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.spec.restartPolicy }}
      securityContext:
        {{- toYaml .Values.spec.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          hostPath:
            path: {{ .Values.spec.volumes.path }}
            type: Directory
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              protocol: {{ .Values.service.protocol }}
          securityContext:
            {{- toYaml .Values.spec.containerSecurityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/openvpn
          env:
            - name: EASYRSA_KEY_SIZE
              value: "4096"