apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
      nodePort: {{ .Values.service.externalPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "openvpn.selectorLabels" . | nindent 4 }}