apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "jdownloader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jdownloader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jdownloader.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: {{ .Values.spec.restartPolicy }}
      securityContext:
        {{- toYaml .Values.spec.podSecurityContext | nindent 8 }}
      volumes:
        {{- toYaml .Values.spec.volumes | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          volumeMounts:
            {{- toYaml .Values.spec.volumeMounts | nindent 12 }}
          env:
            - name: SECURE_CONNECTION
              value: "1"