apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "ground-temperatures-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "ground-temperatures-service.selectorLabels" . | nindent 4 }}