# Number of replicas to de deployed
replicaCount: 1

# Image pull information
image:
  repository: registry
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Data about the service and port used by it
service:
  type: NodePort
  containerPort: 5000
  externalPort: 31050
  protocol: TCP

spec:
  # The app should be working always even when the host restarts unless it is stopped
  restartPolicy: Always
  # Volumes to be configured for configuration and downloads
  volumes:
    # Change <Absolute path> by a valid path
    registryPath: <Absolute path>
  # Path of the shell interpreter. /bin/ash for alpine
  shellPath: /bin/ash
  # List of semi-colon separated commands to execute in shell during initialization
  commands: >
    apk add --no-cache apache2-utils ;
    [ -d /auth ] || mkdir /auth ;
    [ -f /auth/htpasswd ] || htpasswd -b -c -B -C 15 /auth/htpasswd $USER $PASSWORD ;
    /entrypoint.sh /etc/docker/registry/config.yml
  user: user
  password: password