apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.containerPort }}
      targetPort: {{ .Values.service.containerPort }}
      nodePort: {{ .Values.service.externalPort }}
      protocol: TCP
  selector:
    {{- include "plex.selectorLabels" . | nindent 4 }}