# Number of replicas to de deployed
replicaCount: 1

# Image pull information
image:
  repository: weatherstationproject/air-parameter-service
  pullPolicy: IfNotPresent
  pullSecret: regcred
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Data about the service and port used by it
service:
  type: ClusterIP
  containerPort: 1443
  protocol: TCP

spec:
  # The app should be working always even when the host restarts unless it is stopped
  restartPolicy: Always
  # Volume to be configured for certificate path
  volumes:
    # Change <Absolute path> by a valid path
    certificatePath: <Absolute path>

# Probes
livenessProbe:
  httpGet:
    path: /api/health-check
    port: 1443
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 10

readinessProbe:
  httpGet:
    path: /api/health-check
    port: 1443
  initialDelaySeconds: 15
  periodSeconds: 5
  timeoutSeconds: 10

# Resources
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    memory: 512Mi