apiVersion: v1
stringData:
  audienceSecret: {{ .Values.audienceSecret | quote }}
  certificatePassword: {{ .Values.certificatePassword | quote }}
  server: {{ .Values.server | quote }}
  database: {{ .Values.database | quote }}
  user: {{ .Values.user | quote }}
  password: {{ .Values.password | quote }}
kind: Secret
metadata:
  name: global-secrets
type: Opaque