apiVersion: v1
data:
  audienceSecret: {{ .Values.audienceSecret }}
  certificatePassword: {{ .Values.certificatePassword }}
  server: {{ .Values.server }}
  database: {{ .Values.database }}
  user: {{ .Values.user }}
  password: {{ .Values.password }}
kind: Secret
metadata:
  name: global-secrets
type: Opaque