# Number of replicas to de deployed
replicaCount: 1

# Image pull information
image:
  repository: weatherstationproject/authentication-service
  pullPolicy: IfNotPresent
  pullSecret: regcred
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# Data about the service and port used by it
service:
  type: NodePort
  containerPort: 1443
  externalPort: 30045
  protocol: TCP

spec:
  # The app should be working always even when the host restarts unless it is stopped
  restartPolicy: Always
  # Volume to be configured for certificate path
  volumes:
    # Change <Absolute path> by a valid path
    certificatePath: <Absolute path>
  authenticationSecret: 123456